# Generated by Django 5.0.14 on 2026-08-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kakao_id', models.BigIntegerField(unique=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
